version: "3.1"

services:
  db:
    container_name: db
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "bus-ticket"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "5433:80"
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    networks:
      - local

volumes:
  data_postgres:
  data_pgadmin:

networks:
  local: