server:
  port: 8080

spring:
  application:
    name: 'ticket-express'
  datasource:
    url: jdbc:postgresql://localhost:5432/bustickets
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none